prompts:
  generate_dishes:
    system: "Форматируй ответ на запрос как json, содержащий массив из 7 json-объектов, каждый из которых имеет 5 полей \"dish\", \"calories\", \"protein\", \"fats\", \"carbs\"."
    user: "Сгенерируй 7 названия различных ресторанных блюд, а также их правдоподобные характеристики - калории, белки, жиры, углеводы в граммах на 100 грамм продукта. Пример одного ответа: { \"dish\": \"Салат Цезарь с креветками\", \"calories\": 287.9 , \"protein\": 9.1, , \"fats\": 25.7, , \"carbs\": 5.8}."
    temperature: 0.6
  generate_analogues:
    system: "Форматируй ответ на запрос как json, содержащий массив из 5 json-объектов, каждый из которых имеет 5 полей \"dish\", \"calories\", \"protein\", \"fats\", \"carbs\"."
    temperature: 0.75
generated_data_path: "../data_generations/data2"